"""Minimal ports for effects owned outside the XiaoH domain."""

from __future__ import annotations

from contextlib import AbstractContextManager
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Iterable, Mapping, Optional, Protocol, Sequence


class FileSystemPort(Protocol):
    def exists(self, path: Path) -> bool: ...

    def is_file(self, path: Path) -> bool: ...

    def is_dir(self, path: Path) -> bool: ...

    def is_symlink(self, path: Path) -> bool: ...

    def resolve(self, path: Path, strict: bool = False) -> Path: ...

    def read_bytes(self, path: Path) -> bytes: ...

    def read_text(self, path: Path) -> str: ...

    def write_bytes_atomic(self, path: Path, content: bytes) -> None: ...

    def write_text_atomic(self, path: Path, content: str) -> None: ...

    def mkdir(self, path: Path) -> None: ...

    def remove(self, path: Path) -> None: ...

    def copy(self, source: Path, target: Path) -> None: ...

    def replace(self, source: Path, target: Path) -> None: ...

    def iter_files(self, root: Path) -> Iterable[Path]: ...

    def iter_children(self, root: Path) -> Iterable[Path]: ...

    def size(self, path: Path) -> int: ...

    def digest(self, path: Path) -> Optional[str]: ...

    def free_bytes(self, path: Path) -> int: ...

    def chmod_executable(self, path: Path) -> None: ...

    def lock(self, path: Path) -> AbstractContextManager[None]: ...


@dataclass(frozen=True)
class ProcessResult:
    returncode: int
    stdout: str = ""
    stderr: str = ""


class ProcessRunnerPort(Protocol):
    def run(
        self,
        command: Sequence[str],
        env: Optional[Mapping[str, str]] = None,
        cwd: Optional[Path] = None,
    ) -> ProcessResult: ...


class ClockPort(Protocol):
    def now(self) -> datetime: ...


class PluginFactsPort(Protocol):
    def current_facts(self) -> Mapping[str, Any]: ...


class AutomationStorePort(Protocol):
    def get(self, task_id: str) -> Optional[Mapping[str, Any]]: ...

    def create(self, logical_id: str, values: Mapping[str, Any]) -> str: ...

    def update(self, task_id: str, values: Mapping[str, Any]) -> None: ...

    def list(self) -> Sequence[Mapping[str, Any]]: ...
